<?php
require_once __DIR__ . '/../../app/includes/auth.php';
require_admin('../login.php');
require_once __DIR__ . '/../../app/config/db.php';
$conn = (new Database())->connect();
$dailySales = $conn ? $conn->query("SELECT DATE(created_at) AS report_date, COUNT(*) AS orders_count, COALESCE(SUM(total), 0) AS revenue FROM orders GROUP BY DATE(created_at) ORDER BY report_date DESC LIMIT 14")->fetchAll(PDO::FETCH_ASSOC) : [];
$topCustomers = $conn ? $conn->query("SELECT customer_name, customer_email, COUNT(*) AS orders_count, COALESCE(SUM(total), 0) AS revenue FROM orders GROUP BY customer_email, customer_name ORDER BY revenue DESC LIMIT 10")->fetchAll(PDO::FETCH_ASSOC) : [];
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reports</title><link rel="stylesheet" href="../../assets/css/style.css"><link rel="stylesheet" href="../../assets/css/responsive.css"></head>
<body><main class="section"><div class="container"><div class="section-heading section-heading--row"><div><p class="section-kicker">Admin</p><h1>Reports & Analytics</h1></div><button class="button button--secondary" onclick="window.print()">Export PDF</button></div><section class="admin-panel"><h2>Daily Sales Report</h2><div class="cart-table"><div class="cart-row cart-row--head"><span>Date</span><span>Orders</span><span>Revenue</span><span>Report</span><span>Status</span></div><?php foreach ($dailySales as $row): ?><div class="cart-row"><span><?php echo htmlspecialchars($row['report_date']); ?></span><span><?php echo (int) $row['orders_count']; ?></span><span>TZS <?php echo number_format((float) $row['revenue'], 0); ?></span><span>Daily sales</span><span>Ready</span></div><?php endforeach; ?></div></section><section class="admin-panel"><h2>Top Customers</h2><div class="cart-table"><div class="cart-row cart-row--head"><span>Name</span><span>Email</span><span>Orders</span><span>Revenue</span><span>Status</span></div><?php foreach ($topCustomers as $row): ?><div class="cart-row"><span><?php echo htmlspecialchars($row['customer_name']); ?></span><span><?php echo htmlspecialchars($row['customer_email']); ?></span><span><?php echo (int) $row['orders_count']; ?></span><span>TZS <?php echo number_format((float) $row['revenue'], 0); ?></span><span>Ready</span></div><?php endforeach; ?></div></section><p><a href="../dashboard.php">Back to dashboard</a></p></div></main></body></html>
